# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_body', models.TextField()),
                ('article_date', models.DateTimeField()),
                ('article_likes', models.IntegerField(default=0)),
                ('article_dislikes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_body', models.TextField()),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_blog.Article')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password_hash', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_rating', models.IntegerField(default=0)),
                ('user_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('vote', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_blog.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_blog.User')),
            ],
            options={
                'db_table': 'user_article',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_blog.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userarticle',
            unique_together=set([('user', 'article')]),
        ),
    ]
