# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-26 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_article',
            new_name='comment_article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_body',
            new_name='comment_body',
        ),
    ]
